# Config for running xtal_predict.py with (AE-)PocketMiner.
# Usage: python src/xtal_predict.py path/to/this_file.yaml

# Absolute path to the trained model checkpoint.
# After downloading the ae-pocketminer repo, update this to:
# /path/to/ae-pocketminer/models/aepocketminer
nn_path: /mnt/pure/bowmanlab/sizhang/repos/ae-pocketminer/models/aepocketminer

input_pdb_directory: inputs
output_directory: results/aepocketminer

use_attention: True # True = AE-PocketMiner, False = PocketMiner
# save_attention_weights: True              # will save attention weights to a .npy file in the output directory if use_attention is True
# attention_weights_filename: attention_weights.npy   # can be changed to a different filename

debug: False